### ISSUE TITLE
[GTA 3] worldpipeline

### ISSUE THREAD

**Issue by Lethality5001** [aap/skygfx_vc#15]
worldpipeline anything other than leeds causes some parts of the map to disspear depending on how u look

**Comment by aap** [comment]
Never heard of this bug. you have a video maybe? did you make any map changes without clearing cullzone.dat perhaps?

**Comment by Lethality5001** [comment]
> Never heard of this bug. you have a video maybe? did you make any map changes without clearing cullzone.dat perhaps?

what do u mean clearing cullzone.dat? Also many have this problem. Here : https://media.discordapp.net/attachments/902831224991645716/1175774211860602880/8mb.video-2c6-GoaNXzZE.mp4?ex=656c7410&is=6559ff10&hm=ebbde6df0f0483097299390f31b5b5d03c5b8b378df2dc4110a55a951584e1ea&

Also deleting cullzone.dat makes game not want to load savegame

**Comment by aap** [comment]
That does look like a cullzone-related issue to me. don't delete the file but make it empty. i think that'll fix it.

**Comment by Lethality5001** [comment]
> That does look like a cullzone-related issue to me. don't delete the file but make it empty. i think that'll fix it.

how do i make cullzone empty?

**Comment by aap** [comment]
make an empty file, name it cullzone.dat

**Comment by Lethality5001** [comment]
> make an empty file, name it cullzone.dat


![Screenshot 2023-11-19 161737](https://github.com/aap/skygfx_vc/assets/145836476/443f86d1-9ac8-4a8c-8890-8e53ed8d4e56)
 i did that and it still happens ( here is a screenshot with skygfx settings, it seems to be worldpipeline problem ) 
made an empty file and renamed it "cullzone.dat" and placed in data and same thing: ( pls fix )

**Comment by Lethality5001** [comment]
posting a video in a moment

**Comment by Lethality5001** [comment]
https://github.com/aap/skygfx_vc/assets/145836476/01c50d56-59e5-451a-b4cf-5925a4610342

I noticed it happens here, and at Salvatore's mansion and probably some tree around the map And that army guy gates where the tank is

**Comment by aap** [comment]
Well you're the first one to ever report this, so if it's not a cullzone thing i have absolutely no clue what the problem could be, sorry.

**Comment by Lethality5001** [comment]
> Well you're the first one to ever report this, so if it's not a cullzone thing i have absolutely no clue what the problem could be, sorry.

well i am the "first" because i am the only one who went to the direct source on github to talk about it, theres more ppl that have this issue, some from Gesha's discord too. When you put worldpipeline = 2 ( leeds ) it gets fixed but the steets look a bit lifeless without lighting or something

**Comment by aap** [comment]
Still no idea though. I would suggest trying a mostly unmodified game, because again in all those years i've never heard this complaint before.

**Comment by Lethality5001** [comment]
> Still no idea though. I would suggest trying a mostly unmodified game, because again in all those years i've never heard this complaint before.

its not the game itself, its skygfx, i did many reinstalls also i aint alone on this one 
Try it yourself too, its not all locations but key ones, especially salvatore's mansion, the fences and allat

**Comment by aap** [comment]
someone on discord says he had this problem when using skygfx with the III aircraft mod. could that be the case?

**Comment by HeLiOn--PrImE** [comment]
I can confirm that the III aircraft mod is the issue.

**Comment by Lethality5001** [comment]
> someone on discord says he had this problem when using skygfx with the III aircraft mod. could that be the case?

Yes

**Comment by Lethality5001** [comment]
Fixed by removing III Aircraft mod  ( maybe compatibility issues soon update? )

**Comment by aap** [comment]
Would be nice, either here or in III aircraft. strange bug for sure
