### ISSUE TITLE
Leed's trails just wont be turned on

### ISSUE THREAD

**Issue by Sodicious** [aap/skygfx_vc#16]
Even though i've turned on Leed's trails in the .ini file, when i start my game i have to manually switch to it via the debug menu because it turns back into the default PS2 trails effect. This is pretty annoying, i dont wanna go through the process, even if its a small inconvienience, EVERYTIME I START THE GAME. Fix please?

**Comment by aap** [comment]
`trailsSwitch=1` should be all that's needed. i haven't messed with skygfx in ages but i don't see a problem in the code.

**Comment by Sodicious** [comment]
> `trailsSwitch=1` should be all that's needed. i haven't messed with skygfx in ages but i don't see a problem in the code.

Then maybe its because im using the debug menu, ill try to see if removing it fixes anything.

**Comment by Sodicious** [comment]
Theres a semicolon before "trailsswitch=", i have an excuse for this: I wasn't using notepad++ before this. In short, just remove the semicolon and it'll work. I'm not dumb.
